[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = 0

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0.83"
itertools = "0.12.1"
nom = "7.1.3"
rayon = "1.10.0"
regex = "1.10.4"
